openapi: 3.0.0
info:
  title: Simple Petstore
  version: 1.0.0
servers:
  - url: https://petstore3.swagger.io/api/v3
paths:
  /pet/findByStatus:
    get:
      summary: Finds Pets by status
      parameters:
        - in: query
          name: status
          schema:
            type: string
          required: false
          description: Status values that need to be considered for filter
      responses:
        '200':
          description: successful operation
          headers:
            X-RateLimit-Remaining:
              description: calls left
              schema:
                type: integer
        '400':
          description: Invalid status value
  /pet/{petId}:
    get:
      summary: Find pet by ID
      parameters:
        - in: path
          name: petId
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID
        '404':
          description: Pet not found
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api_key
      in: header
security:
  - api_key: []
